spring.application.name=backend
server.port=8080

spring.data.mongodb.database=db_mental_health_care

spring.data.mongodb.auto-index-creation=true
server.error.include-message=always
spring.profiles.include=secret
spring.security.oauth2.client.registration.google.scope=profile,email

server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
app.frontend-url=http://127.0.0.1:5500